import mongoose from 'mongoose';
import ExcelJS from 'exceljs';
import DataAudit from '../models/DataAudit.js';

const COLLECTIONS=['users','branches','outlets','products','sales','customers','customerpayments','priceadjustments','suppliers','purchaseorders','expenses','approvals','journalentries','fueltanks','fuelpumps','fuelshifts','fueldips','fueldeliveries','sitecontents','cashreconciliations','stockmovements','demobatches','payrollruns','smscampaigns','employeerewards'];
const backupGuard=fastify=>[fastify.authenticate,fastify.requirePermission('data.manage','ceo')];
const currencyGuard=fastify=>[fastify.authenticate,fastify.requirePermission('tools.currency.use','ceo')];
let rateCache={key:'',value:null,expires:0};

async function snapshot(){
  const collections={}; for(const name of COLLECTIONS) collections[name]=await mongoose.connection.db.collection(name).find({}).toArray();
  return {format:'razmed-backup',version:1,createdAt:new Date().toISOString(),collections};
}
function validateBackup(data){if(data?.format!=='razmed-backup'||data?.version!==1||!data.collections||typeof data.collections!=='object')throw new Error('Invalid RAZMED backup file');for(const [name,docs] of Object.entries(data.collections))if(!COLLECTIONS.includes(name)||!Array.isArray(docs))throw new Error(`Invalid collection: ${name}`);}
function revive(value,key=''){if(Array.isArray(value))return value.map(x=>revive(x,key));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,revive(v,k)]));if(typeof value==='string'&&/^[a-f\d]{24}$/i.test(value)&&(key==='_id'||/Id$/.test(key)||['branch','branches','outlet','outlets','cashier','customer','product','supplier','employee','attendant','pump','tank','createdBy','updatedBy','submittedBy','reviewedBy','approvedBy','journal','sourceId','reversalOf'].includes(key)))return new mongoose.Types.ObjectId(value);if(typeof value==='string'&&/(At|Date|date)$/.test(key)&&/^\d{4}-\d{2}-\d{2}T/.test(value))return new Date(value);return value;}
async function applyBackup(data,mode){
  validateBackup(data); if(mode==='replace'&&!data.collections.users?.some(u=>u.role==='super_admin'&&u.active!==false))throw new Error('Replacement backup must contain an active Super Admin');
  let records=0; for(const [name,docs] of Object.entries(data.collections)){const collection=mongoose.connection.db.collection(name);if(mode==='replace')await collection.deleteMany({});if(docs.length){const ops=docs.map(doc=>{const value=revive(doc);return {replaceOne:{filter:{_id:value._id},replacement:value,upsert:true}}});await collection.bulkWrite(ops,{ordered:false});records+=docs.length;}}
  return {collections:Object.keys(data.collections).length,records};
}

export default async function toolsRoutes(fastify){
  fastify.get('/api/tools/currency',{preHandler:currencyGuard(fastify)},async(request,reply)=>{
    const from=String(request.query?.from||'USD').toUpperCase(),to=String(request.query?.to||'GHS').toUpperCase(),amount=Number(request.query?.amount||1);if(!/^[A-Z]{3}$/.test(from)||!/^[A-Z]{3}$/.test(to)||!Number.isFinite(amount))return reply.code(400).send({error:'Valid currencies and amount are required'});if(from===to)return {from,to,amount,rate:1,result:amount,date:new Date().toISOString().slice(0,10),source:'Identity'};
    const key=`${from}:${to}`;try{if(rateCache.key!==key||Date.now()>rateCache.expires){const response=await fetch(`https://api.frankfurter.dev/v2/rates?base=${from}&quotes=${to}`,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error('Rate provider unavailable');const rows=await response.json(),item=Array.isArray(rows)?rows.find(x=>x.quote===to):null;if(!item?.rate)throw new Error('Currency pair unavailable');rateCache={key,value:item,expires:Date.now()+15*60*1000};}return {from,to,amount,rate:rateCache.value.rate,result:amount*rateCache.value.rate,date:rateCache.value.date,source:'Frankfurter central-bank rates'};}catch(error){return reply.code(502).send({error:error.message});}
  });
  fastify.get('/api/data/backup',{preHandler:backupGuard(fastify)},async(request)=>{const data=await snapshot();const records=Object.values(data.collections).reduce((s,x)=>s+x.length,0);await DataAudit.create({action:'export',format:'json',collections:Object.keys(data.collections).length,records,performedBy:request.user.id});return data;});
  fastify.get('/api/data/export.xlsx',{preHandler:backupGuard(fastify)},async(request,reply)=>{const data=await snapshot(),workbook=new ExcelJS.Workbook();workbook.creator='RazMed Enterprise Platform';const sheet=workbook.addWorksheet('RAZMED Data');sheet.columns=[{header:'Collection',key:'collection',width:28},{header:'Document JSON',key:'document',width:120}];for(const [name,docs] of Object.entries(data.collections))for(const doc of docs)sheet.addRow({collection:name,document:JSON.stringify(doc)});sheet.getRow(1).font={bold:true};const buffer=await workbook.xlsx.writeBuffer();await DataAudit.create({action:'export',format:'excel',collections:Object.keys(data.collections).length,records:sheet.rowCount-1,performedBy:request.user.id});return reply.header('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').header('Content-Disposition',`attachment; filename="razmed-backup-${new Date().toISOString().slice(0,10)}.xlsx"`).send(Buffer.from(buffer));});
  fastify.post('/api/data/restore',{preHandler:backupGuard(fastify)},async(request,reply)=>{if(request.body?.confirmation!=='RESTORE RAZMED')return reply.code(400).send({error:'Type RESTORE RAZMED to confirm'});try{const result=await applyBackup(request.body.backup,request.body.mode==='replace'?'replace':'merge');await DataAudit.create({action:'restore',format:'json',mode:request.body.mode, ...result,performedBy:request.user.id});return result;}catch(e){return reply.code(400).send({error:e.message});}});
  fastify.post('/api/data/import.xlsx',{preHandler:backupGuard(fastify)},async(request,reply)=>{if(request.body?.confirmation!=='RESTORE RAZMED')return reply.code(400).send({error:'Type RESTORE RAZMED to confirm'});try{const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(Buffer.from(request.body.data,'base64'));const sheet=workbook.getWorksheet('RAZMED Data')||workbook.worksheets[0],collections={};sheet.eachRow((row,n)=>{if(n===1)return;const name=String(row.getCell(1).value||''),raw=String(row.getCell(2).value||'');if(!COLLECTIONS.includes(name)||!raw)return;(collections[name]||=[]).push(JSON.parse(raw));});const backup={format:'razmed-backup',version:1,collections};const result=await applyBackup(backup,request.body.mode==='replace'?'replace':'merge');await DataAudit.create({action:'restore',format:'excel',mode:request.body.mode,...result,performedBy:request.user.id});return result;}catch(e){return reply.code(400).send({error:e.message});}});
  fastify.get('/api/data/audit',{preHandler:backupGuard(fastify)},async()=>DataAudit.find().populate('performedBy','name').sort({createdAt:-1}).limit(50));
}
