import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BatteryCharging, Check, ChevronLeft, ChevronRight, CircleDot, Gauge, MapPin, Menu, Minus, Phone, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Wrench, X, Zap } from 'lucide-react';
import DesktopApp from './DesktopApp.jsx';
import { api } from '../api.js';
import './tailwind.css';

const FALLBACK = [
  { id:'t1',type:'Tyres',name:'Bridgestone Turanza T005',spec:'205/55 R16 · 91V',price:1380,badge:'Passenger' },
  { id:'t2',type:'Tyres',name:'Michelin Primacy 4+',spec:'225/45 R17 · 94W',price:1840,badge:'Premium' },
  { id:'r1',type:'Rims',name:'Apex Alloy Rim',spec:'17 inch · 5×114.3',price:2150,badge:'Alloy' },
  { id:'b1',type:'Batteries',name:'Bosch S4 Battery',spec:'12V · 72Ah · 680CCA',price:1680,badge:'24-month warranty' },
  { id:'l1',type:'Oil & Lubricants',name:'Premium Engine Oil',spec:'5W-30 · 4 litres',price:420,badge:'Engine care' },
];
const money=v=>`GH₵ ${Number(v||0).toLocaleString('en-GH',{minimumFractionDigits:2})}`;
const clean=v=>String(v??'').toLowerCase().replace(/[^a-z0-9]/g,'');
const nums=v=>String(v??'').replace(/\D/g,'');
const match=(q,...values)=>String(q||'').trim().split(/\s+/).filter(Boolean).every(t=>values.some(v=>clean(v).includes(clean(t)))||(nums(t).length>=3&&values.some(v=>nums(v).includes(nums(t)))));
const category=v=>({Tyre:'Tyres',Rim:'Rims',Battery:'Batteries',Lubricant:'Oil & Lubricants',Oil:'Oil & Lubricants'}[v]||v||'Tyres');

function Art({p}){
  if(p.imageUrl)return <img src={p.imageUrl} alt={p.name} className="h-52 w-full object-cover transition duration-500 group-hover:scale-105"/>;
  const Icon=p.type==='Batteries'?BatteryCharging:p.type==='Oil & Lubricants'?Sparkles:CircleDot;
  return <div className="h-52 grid place-items-center bg-[radial-gradient(circle_at_50%_40%,#fff7ed_0%,#f1f5f9_52%,#e2e8f0_100%)]"><Icon size={64} strokeWidth={1.25}/></div>;
}

export default function CorporateWebsiteV2(){
  const [portal,setPortal]=useState(()=>{const s=sessionStorage.getItem('razmed_staff_portal');return s===null?Boolean(localStorage.getItem('razmed_token')):s==='true'});
  const [nav,setNav]=useState(false),[cat,setCat]=useState('All'),[query,setQuery]=useState(''),[cart,setCart]=useState([]),[cartOpen,setCartOpen]=useState(false),[page,setPage]=useState(1),[inventory,setInventory]=useState([]),[content,setContent]=useState({});
  useEffect(()=>{api.storeProducts().then(list=>setInventory(list.map(p=>({id:p._id,type:category(p.category),name:p.name,spec:p.description||p.attributes?.tyreSize||p.code,price:p.price,badge:p.qty>0?`${p.qty} in stock`:'Out of stock',qtyAvailable:p.qty,imageUrl:p.imageUrl,searchValues:[p.name,p.code,p.barcode,p.qrCode,p.description,p.attributes?.brand,p.attributes?.model,p.attributes?.tyreSize]})))).catch(()=>setInventory(FALLBACK));api.siteContent().then(setContent).catch(()=>{})},[]);
  const filtered=useMemo(()=>inventory.filter(p=>(cat==='All'||p.type===cat)&&match(query,...(p.searchValues||[p.name,p.spec]))),[inventory,cat,query]);
  const pageSize=8,pages=Math.max(1,Math.ceil(filtered.length/pageSize)),shown=filtered.slice((page-1)*pageSize,page*pageSize);
  useEffect(()=>setPage(1),[cat,query]);useEffect(()=>{if(page>pages)setPage(pages)},[page,pages]);
  const openPortal=()=>{sessionStorage.setItem('razmed_staff_portal','true');setPortal(true)},closePortal=()=>{sessionStorage.setItem('razmed_staff_portal','false');setPortal(false)};
  const add=p=>setCart(a=>{const f=a.find(i=>i.id===p.id);return f?a.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...a,{...p,qty:1}]});
  const qty=cart.reduce((s,i)=>s+i.qty,0),total=cart.reduce((s,i)=>s+i.price*i.qty,0);
  if(portal)return <div className="relative"><button onClick={closePortal} className="fixed z-[70] top-4 left-4 px-4 py-2.5 rounded-full bg-white border text-xs font-black shadow-xl">← Public website</button><DesktopApp/></div>;
  const categories=[['Tyres',CircleDot,'Grip for every road'],['Rims',Gauge,'Style with strength'],['Batteries',BatteryCharging,'Dependable starts'],['Oil & Lubricants',Sparkles,'Protect every engine']];

  return <div className="razmed-interactive min-h-screen bg-[#f7f5f0] text-[#17191d]" style={{fontFamily:'Arial,Helvetica,sans-serif'}}>
    <div className="bg-[#ff5a14] text-white px-5 py-2.5 text-[11px] font-black uppercase tracking-[.18em] flex justify-between"><span>{content.announcement||'Ghanaian automotive care, fitted with confidence'}</span><span className="hidden md:inline">Accra · Kumasi · Fleet supply</span></div>
    <header className="sticky top-0 z-40 bg-[#f7f5f0]/95 backdrop-blur border-b border-black/10"><div className="max-w-[1450px] mx-auto px-5 lg:px-8 h-24 flex items-center justify-between gap-8"><a href="#home"><img src={content.logoUrl||'/razmed-logo.png'} alt="RazMed Enterprise" className="h-16 w-auto max-w-[230px] object-contain"/></a><nav className="hidden lg:flex gap-9 text-xs font-black uppercase tracking-[.14em]"><a href="#range">Product range</a><a href="#stock">Live stock</a><a href="#care">Auto care</a><a href="#locations">Locations</a></nav><div className="flex gap-2"><button onClick={()=>setCartOpen(true)} className="relative w-12 h-12 rounded-full border border-black/15 grid place-items-center"><ShoppingBag size={19}/>{qty>0&&<span className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-[#ff5a14] text-white text-[10px] font-black grid place-items-center">{qty}</span>}</button><button onClick={openPortal} className="hidden sm:flex h-12 items-center gap-2 px-5 rounded-full bg-[#17191d] text-white text-xs font-black uppercase">Staff access <ArrowRight size={15}/></button><button onClick={()=>setNav(v=>!v)} className="lg:hidden w-12 h-12 rounded-full border grid place-items-center"><Menu size={20}/></button></div></div>{nav&&<nav className="lg:hidden px-6 pb-6 grid gap-4 font-black"><a href="#range">Product range</a><a href="#stock">Live stock</a><a href="#care">Auto care</a><a href="#locations">Locations</a><button onClick={openPortal} className="text-left text-[#ff5a14]">Staff access →</button></nav>}</header>
    <main>
      <section id="home" className="max-w-[1450px] mx-auto px-5 lg:px-8 py-8 lg:py-14"><div className="grid lg:grid-cols-[1.12fr_.88fr] min-h-[650px] overflow-hidden rounded-[2rem] bg-[#17191d]"><div className="relative p-8 sm:p-12 lg:p-16 flex flex-col justify-between text-white overflow-hidden"><div className="absolute -right-24 -top-20 w-80 h-80 rounded-full border-[70px] border-[#ff5a14]/20"/><div className="relative"><p className="inline-flex items-center gap-2 text-[#ff7b42] text-xs font-black uppercase tracking-[.2em]"><Zap size={15}/>{content.heroEyebrow||'Built for Ghanaian roads'}</p><h1 className="mt-7 max-w-3xl text-5xl sm:text-6xl xl:text-[5.5rem] leading-[.92] font-black uppercase tracking-[-.055em]">{content.heroTitle||'Your drive deserves the right fit.'}</h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-slate-300">{content.heroText||'Tyres, rims, batteries and lubricants selected for the way you drive—supported by expert fitting in Accra and Kumasi.'}</p></div><div className="relative mt-12 flex flex-wrap gap-4"><a href="#stock" className="px-7 py-4 rounded-full bg-[#ff5a14] font-black inline-flex gap-3">Explore live stock <ArrowRight size={18}/></a><a href="#locations" className="px-7 py-4 rounded-full border border-white/25 font-bold">Visit a branch</a></div></div><div className="relative min-h-[420px] bg-[#ff5a14] overflow-hidden">{content.heroImageUrl?<img src={content.heroImageUrl} alt="RazMed products" className="absolute inset-0 w-full h-full object-cover mix-blend-multiply opacity-75"/>:<><div className="absolute inset-0 bg-[radial-gradient(circle_at_60%_38%,#ff9b70_0%,#ff5a14_46%,#b93100_100%)]"/><CircleDot className="absolute right-[-12%] top-[6%] w-[100%] h-[88%] text-[#17191d]" strokeWidth={.55}/></>}<div className="absolute inset-x-6 bottom-6 bg-white/95 rounded-2xl p-5 flex justify-between gap-5"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#ff5a14]">Quick fitment search</p><p className="mt-1 font-black">Enter a tyre size or product code</p></div><a href="#stock" className="w-12 h-12 shrink-0 rounded-full bg-[#17191d] text-white grid place-items-center"><Search size={19}/></a></div></div></div></section>
      <section className="max-w-[1450px] mx-auto px-5 lg:px-8 pb-16"><div className="grid grid-cols-2 lg:grid-cols-4 border-y border-black/15">{[['01','Verified stock'],['02','Expert fitting'],['03','Branch pickup'],['04','Fleet support']].map(([n,t])=><div key={n} className="py-7 px-4 border-r border-black/15 flex gap-4"><span className="text-[#ff5a14] text-xs font-black">{n}</span><span className="font-black uppercase text-sm">{t}</span></div>)}</div></section>
      <section id="range" className="bg-white border-y border-black/10"><div className="max-w-[1450px] mx-auto px-5 lg:px-8 py-20"><div className="flex flex-col md:flex-row md:items-end justify-between gap-5"><div><p className="text-xs font-black text-[#ff5a14] uppercase tracking-[.2em]">Shop by need</p><h2 className="mt-3 text-4xl md:text-6xl font-black uppercase tracking-[-.045em]">Four essentials.<br/>One trusted source.</h2></div><p className="max-w-md text-slate-500">A focused automotive range, backed by product guidance, installation and after-sales support.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-px bg-black/10 border border-black/10 mt-12">{categories.map(([name,Icon,sub],i)=><button key={name} onClick={()=>{setCat(name);document.querySelector('#stock')?.scrollIntoView({behavior:'smooth'})}} className="group text-left bg-white p-7 min-h-64 hover:bg-[#ff5a14]"><span className="text-xs font-black text-slate-400 group-hover:text-white/70">0{i+1}</span><Icon size={42} className="mt-10 group-hover:text-white"/><h3 className="mt-8 text-2xl font-black uppercase group-hover:text-white">{name}</h3><p className="mt-2 text-sm text-slate-500 group-hover:text-white/80">{sub}</p></button>)}</div></div></section>
      <section id="stock" className="max-w-[1450px] mx-auto px-5 lg:px-8 py-20"><div className="grid lg:grid-cols-[.7fr_1.3fr] gap-10 items-end"><div><p className="text-xs font-black text-[#ff5a14] uppercase tracking-[.2em]">Connected inventory</p><h2 className="mt-3 text-4xl md:text-6xl font-black uppercase tracking-[-.045em]">Available<br/>right now.</h2></div><div><div className="bg-white border-2 border-[#17191d] rounded-full p-2 pl-5 flex items-center gap-3"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search 2055516, brand, product name or code" className="flex-1 min-w-0 py-2 outline-none bg-transparent"/><span className="hidden sm:block px-6 py-3 rounded-full bg-[#17191d] text-white text-xs font-black">FIND PRODUCT</span></div><div className="mt-4 flex flex-wrap gap-2">{['All',...categories.map(x=>x[0])].map(c=><button key={c} onClick={()=>setCat(c)} className={`px-4 py-2 rounded-full text-xs font-black border ${cat===c?'bg-[#ff5a14] border-[#ff5a14] text-white':'border-black/15'}`}>{c}</button>)}</div></div></div><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-5 mt-12">{shown.map((p,i)=><article key={p.id} className="group bg-white border border-black/10 overflow-hidden rounded-t-[4rem] rounded-b-2xl"><div className="relative overflow-hidden"><Art p={p}/><span className="absolute top-4 left-4 px-3 py-1.5 rounded-full bg-white text-[10px] font-black uppercase">{p.type}</span><span className="absolute top-4 right-4 w-8 h-8 rounded-full bg-[#17191d] text-white text-[10px] font-black grid place-items-center">{String((page-1)*pageSize+i+1).padStart(2,'0')}</span></div><div className="p-5"><p className={`text-[10px] font-black uppercase ${p.qtyAvailable?'text-emerald-700':'text-red-600'}`}>{p.badge}</p><h3 className="mt-2 text-lg font-black min-h-12">{p.name}</h3><p className="mt-2 text-xs text-slate-500 min-h-8">{p.spec}</p><div className="mt-5 pt-4 border-t flex items-center justify-between"><b>{money(p.price)}</b><button disabled={!p.qtyAvailable} onClick={()=>add(p)} className="w-11 h-11 rounded-full bg-[#ff5a14] disabled:bg-slate-300 text-white grid place-items-center"><Plus size={18}/></button></div></div></article>)}</div>{!shown.length&&<div className="py-20 text-center font-black">No matching products found</div>}{pages>1&&<div className="mt-10 flex items-center justify-center gap-3"><button disabled={page===1} onClick={()=>setPage(v=>v-1)} className="w-11 h-11 rounded-full border grid place-items-center"><ChevronLeft/></button><b className="text-xs">PAGE {page} / {pages}</b><button disabled={page===pages} onClick={()=>setPage(v=>v+1)} className="w-11 h-11 rounded-full border grid place-items-center"><ChevronRight/></button></div>}</section>
      <section id="care" className="bg-[#17191d] text-white"><div className="max-w-[1450px] mx-auto px-5 lg:px-8 py-20 grid lg:grid-cols-[.8fr_1.2fr] gap-14"><div><p className="text-xs font-black text-[#ff7b42] uppercase tracking-[.2em]">RazMed auto care</p><h2 className="mt-3 text-4xl md:text-6xl font-black uppercase tracking-[-.045em]">From selection<br/>to installation.</h2><p className="mt-6 text-slate-400">The right product, professionally installed and supported after purchase.</p></div><div className="divide-y divide-white/15 border-y border-white/15">{[[Search,'Match','We identify the right size, specification and price for your vehicle.'],[Wrench,'Fit','Technicians install, balance and check before you leave.'],[ShieldCheck,'Support','Warranty and purchase records stay connected to your profile.']].map(([Icon,title,body],i)=><div key={title} className="py-7 grid md:grid-cols-[48px_150px_1fr] gap-5"><span className="w-12 h-12 rounded-full bg-[#ff5a14] grid place-items-center"><Icon size={20}/></span><h3 className="text-xl font-black uppercase"><small className="text-[#ff7b42] mr-2">0{i+1}</small>{title}</h3><p className="text-sm text-slate-400">{body}</p></div>)}</div></div></section>
      <section id="locations" className="bg-[#ff5a14]"><div className="max-w-[1450px] mx-auto px-5 lg:px-8 py-20"><p className="text-xs font-black uppercase tracking-[.2em]">Find RazMed</p><h2 className="mt-3 text-4xl md:text-6xl font-black uppercase tracking-[-.045em]">Two cities. One standard.</h2><div className="grid md:grid-cols-2 gap-5 mt-12">{[['Accra','Greater Accra Region','Retail · fitting · fleet enquiries'],['Kumasi','Ashanti Region','Retail · fitting · branch pickup']].map(([city,region,services],i)=><article key={city} className="bg-[#f7f5f0] rounded-[2rem] p-8 flex justify-between"><div><span className="text-xs font-black">0{i+1}</span><h3 className="mt-6 text-4xl font-black uppercase">{city}</h3><p className="mt-2 text-sm font-bold text-slate-500">{region}</p><p className="mt-6 text-sm">{services}</p></div><div className="flex flex-col justify-between items-end"><MapPin size={34}/><a href={`tel:${content.phone||''}`} className="w-12 h-12 rounded-full bg-[#17191d] text-white grid place-items-center"><Phone size={18}/></a></div></article>)}</div></div></section>
    </main>
    <footer className="max-w-[1450px] mx-auto px-5 lg:px-8 py-12"><div className="flex flex-col md:flex-row justify-between gap-8"><img src={content.logoUrl||'/razmed-logo.png'} alt="RazMed Enterprise" className="h-16 w-auto object-contain"/><div className="md:text-right"><p className="font-black uppercase">Drive ready. Every day.</p><p className="mt-2 text-sm text-slate-500">Tyres · Rims · Batteries · Lubricants · Automotive care</p><button onClick={openPortal} className="mt-5 text-xs font-black uppercase text-[#ff5a14]">Staff portal →</button></div></div><div className="mt-10 pt-5 border-t flex justify-between text-[11px] font-bold text-slate-500"><span>© {new Date().getFullYear()} RazMed Enterprise</span><span>Accra · Kumasi · Ghana</span></div></footer>
    {cartOpen&&<div className="fixed inset-0 z-50 bg-black/55 flex justify-end" onClick={()=>setCartOpen(false)}><aside className="w-full max-w-md h-full bg-[#f7f5f0] p-6 flex flex-col" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs text-[#ff5a14] uppercase font-black">Branch order</p><h2 className="text-2xl font-black uppercase">Your selection</h2></div><button onClick={()=>setCartOpen(false)} className="w-11 h-11 rounded-full border grid place-items-center"><X/></button></div><div className="flex-1 overflow-auto mt-7 space-y-3">{!cart.length?<div className="h-full grid place-items-center font-black">Your selection is empty</div>:cart.map(item=><div key={item.id} className="bg-white border rounded-2xl p-4"><b>{item.name}</b><p className="text-xs text-slate-500">{item.spec}</p><div className="mt-4 flex justify-between"><b>{money(item.price*item.qty)}</b><div className="flex gap-3"><button onClick={()=>setCart(a=>a.flatMap(i=>i.id!==item.id?[i]:i.qty>1?[{...i,qty:i.qty-1}]:[]))}><Minus size={15}/></button><b>{item.qty}</b><button onClick={()=>add(item)}><Plus size={15}/></button></div></div></div>)}</div><div className="pt-5 border-t"><div className="flex justify-between text-xl font-black"><span>Total</span><span>{money(total)}</span></div><button disabled={!cart.length} className="mt-4 w-full py-4 rounded-full bg-[#ff5a14] disabled:bg-slate-300 text-white font-black flex justify-center gap-2"><Check/> Request branch confirmation</button></div></aside></div>}
  </div>;
}
